### ISSUE TITLE
Crear formulario de registro

### ISSUE THREAD

**Issue by nico-sorice** [nico-sorice/revista-web-2#7]
- [x] Crear usuario en la bdd en caso satisfactorio
- [x] Verificar email no repetido
- [x] Pagina de transicion despues de registrado
- [x] Validaciones Javascript [Todavia NO]
- [X] Llevar por defecto los selected correctos en pais etc
- [ ] Boton de envio en rojo si hay errores
- [x] Revalidar password2 al cambiar password1
- [x] Forzar onchanges cuando hay keypess con focus
- [x] Hacer funcionar el onchange cuando hay focus (cuando recien haces click no valida)

**Comment by nico-sorice** [comment]
Terminando validaciones, faltaria defiinir la contraseña y bueno escribir en la base el nuevo usuario en caso correcto.

**Comment by nico-sorice** [comment]
Falta:
Crear usuario en la bdd en caso satisfactorio
Verificar email no repetido
Pagina de transicion despues de registrado
Validaciones Javascript [Todavia NO]
Llevar por defecto los selected correctos en pais etc
Creo que nada mas

**Comment by nico-sorice** [comment]
Faltan solo las validaciones JS

**Comment by nico-sorice** [comment]
@gciancio .Gonza fijate si podes meter las validaciones javascript al formulario de registro, (Mientras va escribiendo que aparezca un iconito o algo al lado que te diga que esta mal o bien), Ahora veo si llego y te dejo el primero de ejemplo.

El archivo en cuestion es js/validarRegistro.js, ya esta cargado en registro.php y las validaciones php ya estan echas en include/validar.class.php ahi tenes los criterios de validacion.

Cualquier cosa preguntame.

**Comment by nico-sorice** [comment]
Ahi te deje un ejemplo que valida el primero!

**Comment by gciancio** [comment]
Listo la validación de JS, faltaría ver que se hace con los 3 select aunque seguramente quede como están.

**Comment by nico-sorice** [comment]
Buenisimo, quedo genial!! lo vuelvo a abrir y le agrego una bldes q nos faltaria ponerle que es qu el boton de envio se ponga rojo si hay errores, y que actualize la validacion de la segunda password de acuerdo a la primera, y que cuando esten con focus, al apretar una tecla actualice la validacion tambien.

**Comment by nico-sorice** [comment]
Che no sabia que te llegan mails cuando alguien agrega y borra estas cosas, osea que tipo 3 am te llegaban mails mios? jaja perdon!
